meta_product_name: "Banded"
meta_title: "Banded | Join Forces, Make Music"
meta_description: "Connect with passionate musicians, form bands, and create extraordinary music together. Join Banded now and unleash your musical potential."
meta_image: "og_image.jpg" # should exist in `app/assets/images/`
